live_config_reload = true

# themes
import = ["~/.config/alacritty/themes/dracula/dracula.toml"]

[font]
size = 18

[font.normal]
family = "0xProtoNerdFont"

[font.bold]
family = "0xProtoNerdFont"
style = "Bold"

[font.italic]
family = "0xProtoNerdFont"
style = "italic"

[scrolling]
history = 2000
multiplier = 20

[shell]
args = ["-l"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"
opacity = 0.85

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 1 
y = 1
