live_config_reload = true

[font]
size = 12

[font.bold]
family = "Agave Nerd Font Mono"
style = "Bold"

[font.normal]
family = "Agave Nerd Font Mono"
style = "Regular"

[scrolling]
history = 2000
multiplier = 20

[shell]
args = ["-l"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 10
y = 15
