live_config_reload = true

# # themes
# import = ["~/.config/alacritty/themes/dracula/dracula.toml"]
#
# [font]
# size = 18
#
# [font.normal]
# family = "0xProtoNerdFont"
#
# [font.bold]
# family = "0xProtoNerdFont"
# style = "Bold"
#
# [font.italic]
# family = "0xProtoNerdFont"
# style = "italic"
#
# [scrolling]
# history = 2000
# multiplier = 20
#
# [shell]
# args = ["-l"]
# program = "/usr/bin/zsh"
#
# [window]
# decorations = "full"
# dynamic_padding = false
# startup_mode = "Maximized"
# opacity = 0.7
# blur = true
# [window.dimensions]
# columns = 120
# lines = 60
#
# [window.padding]
# x = 1 
# y = 1

import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
    # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

[font]
size = 18 
normal.family = "0xProtoNerdFont"

[shell]
args = ["-l"]
program = "/usr/bin/zsh"
#for video
# size = 35.0
