live_config_reload = true

# themes
import = ["~/.config/alacritty/themes/dracula/dracula.toml"]

[font]
size = 20

[font.normal]
family = "MesloLGS NF"

# [font.bold]
# family = "Jet Brains Mono Nerd Font"
# style = "Bold"

# [font.normal]
# family = "Jet Brains Mono Nerd Font"
# style = "Regular"

# [font.italic]
# family = "Jet Brains Mono Nerd Font Italic"
# style = "italic"

[scrolling]
history = 2000
multiplier = 20

[shell]
args = ["-l"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"
# opacity = 0.8

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 1 
y = 1
